# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  metricsproxyweb:
    image: metricsproxyweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - METRICSPROXY_DataSink__Databox__Token=${DATABOX_TOKEN}
      - METRICSPROXY_DataSink__RandomlyFailing__FailureRatePercent=100
      - METRICSPROXY_DataSource__GitHub__AccessToken=${GITHUB_ACCESSTOKEN}
      - METRICSPROXY_DataSource__Facebook__AppId=${FACEBOOK_APPID}
      - METRICSPROXY_DataSource__Facebook__AppSecret=${FACEBOOK_APPSECRET}
      - METRICSPROXY_DatabaseProvider=EfCore # InMemory | EfCore | EfCore_Reset
      - METRICSPROXY_QueryService__IntervalInMilliseconds=60000